// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
require('selenium-webdriver/chrome')
require('chromedriver')

describe('holaprobando', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('holaprobando', async function() {
    await driver.get("http://zero.webappsecurity.com/feedback.html")
    await driver.manage().window().setRect({ width: 1050, height: 700 })
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("holas34")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("kjbdsoid")
    await driver.findElement(By.id("subject")).click()
    await driver.findElement(By.id("subject")).sendKeys("ihfdbiwe")
    await driver.findElement(By.id("comment")).click()
    await driver.findElement(By.id("comment")).sendKeys("kdhbiedb")
    await driver.findElement(By.name("submit")).click()
  })
})
